WebApp/Models/MesDonsViewModel.cs
using Fr.EQL.AI110.DLD_GC.Entities;

namespace Fr.EQL.AI110.DLD_GC.WebApp.Models
{
    public class MesDonsViewModel
    {
        public List<DonDetails>? Dons { get; set; }
        public List<AdherentDetails>? Adherents { get; set; }
        public int? SelectedAdherentId { get; set; }
        public int? AdherentRole { get; set; } = 0;
    }
}

WebApp/Controllers/CatalogController.cs
using Fr.EQL.AI110.DLD_GC.Entities;
using Fr.EQL.AI110.DLD_GC.Business;
using Fr.EQL.AI110.DLD_GC.WebApp.Models;
using Microsoft.AspNetCore.Mvc;

namespace Fr.EQL.AI110.DLD_GC.WebApp.Controllers
{
    public class CatalogController : Controller
    {
        //ACCUEIL
        public IActionResult Main()
        {
            return View();
        }

        //RECHERCHE
        [HttpGet]
        public IActionResult FeL(string rayonSelector, int rayonId)
        {
            // récupérer le modele
            DonSearchViewModel model = new DonSearchViewModel();
            CategorieBusiness catBU = new CategorieBusiness();
            ProduitBusiness proBU = new ProduitBusiness();
            DonBusiness donBU = new DonBusiness();

            model.RayonSelector = rayonSelector;
            model.Rayon = rayonId;

            if (model.Rayon != 0)
            {
                model.SearchCriteria.CatId = model.Rayon;
            }
            else
            {
                model.SearchCriteria.CatId = null;
            }
            if (model.Categorie != 0)
            {
                model.SearchCriteria.Cat2Id = model.Categorie;
            }
            else
            {
                model.SearchCriteria.Cat2Id = null;
            }
            if (model.SousCategorie != 0)
            {
                model.SearchCriteria.Cat3Id = model.SousCategorie;
            }
            else
            {
                model.SearchCriteria.Cat3Id = null;
            }

            model.Categories2 = catBU.GetCat2byParentId(model.Rayon);
            model.Categories3 = catBU.GetCat3byParentId(model.Categorie);
            model.Produits = proBU.GetProduitbyParentId(model.SousCategorie);
            //model.Produits = proBU.GetProduitDetails();

            model.Dons = donBU.SearchDons(model.SearchCriteria);

            // charger la vue :
            return View(model);
        }

        [HttpPost]
        public IActionResult FeL(DonSearchViewModel model)
        {
            CategorieBusiness catBU = new CategorieBusiness();
            ProduitBusiness proBU = new ProduitBusiness();
            DonBusiness donBU = new DonBusiness();

            if (model.Rayon != 0)
            {
                model.SearchCriteria.CatId = model.Rayon;
            }
            else
            {
                model.SearchCriteria.CatId = null;
            }
            if (model.Categorie != 0)
            {
                model.SearchCriteria.Cat2Id = model.Categorie;
            }
            else
            {
                model.SearchCriteria.Cat2Id = null;
            }
            if (model.SousCategorie != 0)
            {
                model.SearchCriteria.Cat3Id = model.SousCategorie;
            }
            else
            {
                model.SearchCriteria.Cat3Id = null;
            }

            model.Categories2 = catBU.GetCat2byParentId(model.Rayon);
            model.Categories3 = catBU.GetCat3byParentId(model.Categorie);
            model.Produits = proBU.GetProduitbyParentId(model.SousCategorie);
            
            model.Dons = donBU.SearchDons(model.SearchCriteria);

            return View(model);
        }

        //MES DONS
        [HttpGet]
        public IActionResult MesDons()
        {
            MesDonsViewModel model = new MesDonsViewModel();
            AdherentBusiness adhBus = new AdherentBusiness();
            DonBusiness donBus = new DonBusiness();
            model.Adherents = adhBus.GetAllAdherentDetails();
            DonMultiSearch donMultiSearch = new DonMultiSearch();
            model.Dons = donBus.SearchDons(donMultiSearch);
            model.AdherentRole = 0;
            model.SelectedAdherentId = 0;
            return View(model);
        }

        [HttpPost]
        public IActionResult MesDons(MesDonsViewModel model)
        {
            AdherentBusiness adhBus = new AdherentBusiness();
            DonBusiness donBus = new DonBusiness();

            model.Adherents = adhBus.GetAllAdherentDetails();
            DonMultiSearch donMultiSearch = new DonMultiSearch();
            if (model.SelectedAdherentId == 0)
            {
                model.Dons = donBus.SearchDons(donMultiSearch);
                model.AdherentRole = 0;
                model.SelectedAdherentId = 0;
                return View(model);
            }
            if (model.AdherentRole == 0)
            {
                model.Dons = donBus.SearchByImplicatedAdherentId((int)model.SelectedAdherentId);
            }
            else if (model.AdherentRole == 1)
            {
                model.Dons = donBus.SearchByDonor(model.SelectedAdherentId);
            }
            else
            {
                model.Dons = donBus.SearchByBeneficiary(model.SelectedAdherentId);
            }
            return View(model);
        }

    }
}

WebApp/Controllers/DonController.cs
using Fr.EQL.AI110.DLD_GC.Entities;
using Fr.EQL.AI110.DLD_GC.Business;
using Fr.EQL.AI110.DLD_GC.WebApp.Models;
using Microsoft.AspNetCore.Mvc;

namespace Fr.EQL.AI110.DLD_GC.WebApp.Controllers
{
    public class DonController : Controller
    {

        [HttpGet]
        public IActionResult ConfirmStockage(int donId)
        {
            DonBusiness dbu = new DonBusiness();
            DonDetails don = dbu.GetDonDetailsById(donId);
            dbu.ConfirmationDepositInAStorageSpaceDon(don);
            return View("Stockage", don);
        }

        [HttpPost]
        public IActionResult ConfirmStockage(DonDetails don)
        {
            DonDetailsViewModel model = new DonDetailsViewModel();

            if (ModelState.IsValid)
            {
                try
                {
                    DonBusiness dbu = new DonBusiness();
                    model.DonDetails = don;
                    model.SelectedAdherentId = don.BeneficiaryId;
                    return RedirectToAction("Details", new { donId = model.DonDetails.Id, adherentId = model.SelectedAdherentId });
                }
                catch (Exception ex)
                {
                    ViewBag.ErrorMessage = ex.Message;
                    return View("Stockage", don);
                }

            }
            else
            {
                return View("Stockage", don);
            }
        }

        [HttpGet]
        public IActionResult ConfirmHandover(int donId)
        {
            DonBusiness dbu = new DonBusiness();
            DonDetails don = dbu.GetDonDetailsById(donId);
            dbu.ConfirmationEchangeDonorDon(don);
            return View("Transfert", don);
        }

        [HttpPost]
        public IActionResult ConfirmHandover(DonDetails don)
        {
            DonDetailsViewModel model = new DonDetailsViewModel();

            if (ModelState.IsValid)
            {
                try
                {
                    DonBusiness dbu = new DonBusiness();
                    model.DonDetails = don;
                    model.SelectedAdherentId = don.BeneficiaryId;
                    return RedirectToAction("Details", new { donId = model.DonDetails.Id, adherentId = model.SelectedAdherentId });
                }
                catch (Exception ex)
                {
                    ViewBag.ErrorMessage = ex.Message;
                    return View("Transfert", don);
                }

            }
            else
            {
                return View("Transfert", don);
            }
        }

        [HttpGet]
        public IActionResult ConfirmReceived(int donId)
        {
            DonBusiness dbu = new DonBusiness();
            DonDetails don = dbu.GetDonDetailsById(donId);
            dbu.ConfirmationEchangeBeneficiaryDon(don);
            return View("Reception", don);
        }

        [HttpPost]
        public IActionResult ConfirmReceived(DonDetails don)
        {
            DonDetailsViewModel model = new DonDetailsViewModel();

            if (ModelState.IsValid)
            {
                try
                {
                    DonBusiness dbu = new DonBusiness();
                    model.DonDetails = don;
                    model.SelectedAdherentId = don.BeneficiaryId;
                    return RedirectToAction("Details", new { donId = model.DonDetails.Id, adherentId = model.SelectedAdherentId });
                }
                catch (Exception ex)
                {
                    ViewBag.ErrorMessage = ex.Message;
                    return View("Reception", don);
                }

            }
            else
            {
                return View("Reception", don);
            }
        }

        [HttpGet]
        public IActionResult CancelReservation(int donId)
        {
            DonBusiness dbu = new DonBusiness();
            DonDetails don = dbu.GetDonDetailsById(donId);
            dbu.CancelReservationDon(don);
            return View("CancelReserve", don);
        }

        [HttpPost]
        public IActionResult CancelReservation(DonDetails don)
        {
            DonDetailsViewModel model = new DonDetailsViewModel();

            if (ModelState.IsValid)
            {
                try
                {
                    DonBusiness dbu = new DonBusiness();
                    model.DonDetails = don;
                    model.SelectedAdherentId = don.BeneficiaryId;
                    return RedirectToAction("Details", new { donId = model.DonDetails.Id, adherentId = model.SelectedAdherentId });
                }
                catch (Exception ex)
                {
                    ViewBag.ErrorMessage = ex.Message;
                    return View("CancelReserve", don);
                }

            }
            else
            {
                return View("CancelReserve", don);
            }
        }

        //[HttpGet]
        //public IActionResult MakeAReservation(int id)
        //{
        //    DonBusiness dbu = new DonBusiness();
        //    DonDetails don = dbu.GetDonDetailsById(id);

        //    return View ("Reserve", don);
        //}

        [HttpGet]
        public IActionResult MakeAReservation(int donId, int beneficiaryId)
        {
            DonBusiness dbu = new DonBusiness();
            dbu.MakeAReservationWithBeneficiaryId(donId, beneficiaryId);
            DonDetails don = dbu.GetDonDetailsById(donId);

            return View("Reserve", don);
        }
        
        [HttpPost]
        public IActionResult MakeAReservation(DonDetails don)
        {
            DonDetailsViewModel model = new DonDetailsViewModel();
            if (ModelState.IsValid)
            {
                try
                {
                    DonBusiness dbu = new DonBusiness();
                    model.DonDetails = don;
                    model.SelectedAdherentId = don.BeneficiaryId;
                    return RedirectToAction("Details",new {donId=model.DonDetails.Id,adherentId=model.DonDetails.BeneficiaryId});
                }
                catch (Exception ex)
                {
                    ViewBag.ErrorMessage = ex.Message;
                    return View("Reserve", don);
                }

            }
            else
            {
                return View("Reserve", don);
            }
        }
        
        /*
        private IActionResult EditerDon(string rubrique, Don don)
        {
            ViewBag.Rubrique = rubrique;
            return View("New", don);
        }
        */
        
        [HttpGet]
        public IActionResult Update(int id)
        {
            DonBusiness dbu = new DonBusiness();
            DonDetails don = dbu.GetDonDetailsById(id);

            return View("Maj", don);
        }

        [HttpPost]
        public IActionResult Update(DonDetails don)
        {
            if (1 == 1)
            {
                try
                {
                    DonBusiness dbu = new DonBusiness();
                    dbu.UpdateDon(don);
                    return RedirectToAction("Details", don);
                }
                catch (Exception ex)
                {
                    ViewBag.ErrorMessage = ex.Message;
                    return View("Maj", don);
                }

            }
            else
            {
                return View ("Maj", don);
            }
        }

        #region CREATE


        /*
        [HttpGet]
        public IActionResult Create()
        {
            return NEW(null);
        }
        [HttpPost]
        public IActionResult Create(DonDetails don)
        {
            if (ModelState.IsValid)
            {
            DonBusiness bu = new DonBusiness();
            bu.Insert(don);
            return RedirectToAction("Details");
        }
            else
            {
                // si pas valide, j'affiche à nouveau la vue :
                return New(don);
            }
        }
        */
        #endregion

        #region READ
        //RECHERCHE MULTICRITERE
        [HttpGet]
        public IActionResult Search()
        {
            // récupérer le modele
            DonSearchViewModel model = new DonSearchViewModel();

            CategorieBusiness catBU = new CategorieBusiness();
            ProduitBusiness proBU = new ProduitBusiness();
            model.Categories = catBU.GetCategories();
            model.Categories2 = catBU.GetCategories2();
            model.Categories3 = catBU.GetCategories3();

            model.Produits = proBU.GetProduitDetails();

            DonBusiness donBU = new DonBusiness();
            model.Dons = donBU.SearchDons(model.SearchCriteria);

            // charger la vue :
            return View(model);
        }

        [HttpPost]
        public IActionResult Search(DonSearchViewModel model)
        {
            CategorieBusiness catBU = new CategorieBusiness();
            ProduitBusiness proBU = new ProduitBusiness();
            model.Categories = catBU.GetCategories();
            model.Categories2 = catBU.GetCat2byParentId(model.Rayon);
            model.Categories3 = catBU.GetCat3byParentId(model.Categorie);
            model.Produits = proBU.GetProduitbyParentId(model.SousCategorie);

            DonBusiness donBU = new DonBusiness();
            model.Dons = donBU.SearchDons(model.SearchCriteria);

            return View(model);
        }

        [HttpGet]
        public IActionResult CancelDon(int donId, int beneficiaryId)
        {
            DonBusiness dbu = new DonBusiness();
            dbu.CancelDonDon(donId);
            DonDetails don = dbu.GetDonDetailsById(donId);

            return View("CancelDon", don);
        }

        [HttpPost]
        public IActionResult CancelDon(DonDetails don)
        {
            DonDetailsViewModel model = new DonDetailsViewModel();
            if (ModelState.IsValid)
            {
                try
                {
                    DonBusiness dbu = new DonBusiness();

WebApp/Views/Catalog/FeL.cshtml
@using Fr.EQL.AI110.DLD_GC.Entities
@using Fr.EQL.AI110.DLD_GC.WebApp.Models
@model DonSearchViewModel

<body class=@Model.RayonSelector>
    <article>
        <form method="post">
            <input asp-for="SearchCriteria.ProduitName" placeholder="Recherche rapide"></input>
            <input type="submit" value="Rechercher" />
            <nav class="catalog">
                <a class="item" asp-controller="Catalog" asp-action="FeL" asp-route-rayonSelector="FeL" asp-route-rayonId="1">
                    <div class="FeL2">
                    </div>
                </a>
                <a class="item" asp-controller="Catalog" asp-action="FeL" asp-route-rayonSelector="VeP" asp-route-rayonId="2">
                    <div class="VeP2">
                    </div>
                </a>
                <a class="item" asp-controller="Catalog" asp-action="FeL" asp-route-rayonSelector="PeP" asp-route-rayonId="3">
                    <div class="PeP2">
                    </div>
                </a>
                <a class="item" asp-controller="Catalog" asp-action="FeL" asp-route-rayonSelector="F" asp-route-rayonId="4">
                    <div class="F2">
                    </div>
                </a>
                <a class="item" asp-controller="Catalog" asp-action="FeL" asp-route-rayonSelector="S" asp-route-rayonId="5">
                    <div class="S2">
                    </div>
                </a>
                <a class="item" asp-controller="Catalog" asp-action="FeL" asp-route-rayonSelector="B" asp-route-rayonId="6">
                    <div class="B2">
                    </div>
                </a>
                <a class="item" asp-controller="Catalog" asp-action="FeL" asp-route-rayonSelector="ESalee" asp-route-rayonId="7">
                    <div class="ESalee2">
                    </div>
                </a>
                <a class="item" asp-controller="Catalog" asp-action="FeL" asp-route-rayonSelector="ESucree" asp-route-rayonId="8">
                    <div class="ESucree2">
                    </div>
                </a>
            </nav>

            <nav class="filterSearch">
                <select hidden asp-for="Rayon">
                    <option hidden selected value="@Model.Rayon"></option>
                </select>
                <div class="left">
                    <div>
                        Catégorie :
                        <br />
                        <select asp-for="@Model.Categorie">
                            <option value="">All...</option>
                            @foreach (Categorie2 cat in Model.Categories2)
                            {
                                <option value="@cat.Id">@cat.Name</option>
                            }
                        </select>
                    </div>
                    @if (Model.Categorie != 0)
                    {
                        <div>
                            Sous-catégorie :
                            <br />
                            <select asp-for="@Model.SousCategorie">
                                <option value="">All...</option>
                                @foreach (Categorie3 cat in Model.Categories3)
                                {
                                    <option value="@cat.Id">@cat.Name</option>
                                }
                            </select>
                        </div>
                    }
                    @if (Model.SousCategorie != 0 && Model.Categorie != 0)
                    {
                        <div>
                            Produit :
                            <br />
                            <select asp-for="SearchCriteria.ProduitId">
                                <option value="">All...</option>
                                @foreach (ProduitDetails pro in Model.Produits)
                                {
                                    <option value="@pro.Id">@pro.Name</option>
                                }
                            </select>
                        </div>
                    }
                    <div>
                        Quantité :
                        <br />
                        <input asp-for="SearchCriteria.Qty"></input>
                    </div>
                </div>
                <div class="right">
                    Date limite de consommation (DLC) :
                    <br />
                    Min <input asp-for="SearchCriteria.DlcMin"></input>
                    Max <input asp-for="SearchCriteria.DlcMax"></input>
                    <br />
                    Date de durabilité minimale (DDM):
                    <br />
                    Min <input asp-for="SearchCriteria.DdmMin"></input>
                    Max <input asp-for="SearchCriteria.DdmMax"></input>
                </div>
            </nav>
        </form>

        <nav class="searchResult">
            @foreach (DonDetails don in Model.Dons)
            {
                if (don.ReserveDate == null && don.CancelDate == null)
                {
                    <article class="mesdonsarticle">
                        <header>
                            <a style="text-decoration:none; color:black;" asp-controller="Don"
                   asp-action="Details"
                   asp-route-donId="@don.Id"
                   asp-route-adherentId="@don.DonorId">
                                <img class="mesdonsimage" src="/images/@don.DonorId/@don.Picture" alt="" onerror="this.onerror=null; this.src='/images/default.png'">
                            </a>
                        </header>
                        <span>
                            <a style="text-decoration:none; color:black;" asp-controller="Don"
                       asp-action="Details"
                       asp-route-donId="@don.Id"
                       asp-route-adherentId="@don.DonorId">
                                
                                @*<a style="text-decoration:none; color:black;" href="../Don/Details/@don.Id">*@

                                <h1>@don.ProduitName, @don.Qty @don.UniteName</h1>
                            </a>
                            @*</a>*@
                        </span>
                        <span>
                            @if (!don.Dlc.Equals(null))
                            {
                                <p>DLC: @don.Dlc</p>
                            }
                            else if (!don.Ddm.Equals(null))
                            {
                                <p>DDM: @don.Ddm</p>
                            }
                        </span>
                        <span>
                            @if (!don.AltStreetNb.Equals(null))
                            {
                                <p>
                                    @don.AltStreetNb @don.AltStreetName @don.AltCompAdr <br>
                                    @don.DonPostcode @don.DonCity
                                </p>
                            }
                            else if (!don.RelStreetNb.Equals(null))
                            {
                                <p>
                                    @don.RelStreetNb @don.RelStreetName @don.RelCompAdr <br>
                                    @don.RelaisPostcode @don.RelaisCity
                                </p>
                            }
                            else if (!don.PartStreetNb.Equals(null))
                            {
                                <p>
                                    @don.PartStreetNb @don.PartStreetName @don.PartCompAdr <br>
                                    @don.PartPostcode @don.PartCity
                                </p>
                            }
                            else
                            {
                                <p>
                                    @don.DonorStreetNb @don.DonorStreetName @don.DonorCompAdr <br>
                                    @don.DonorPostcode @don.DonorCity
                                </p>
                            }
                        </span>
                    </article>
                }
            }
        </nav>
    </article>
</body>

WebApp/Views/Catalog/Main.cshtml
@using Fr.EQL.AI110.DLD_GC.Entities
@using Fr.EQL.AI110.DLD_GC.WebApp.Models
@model DonSearchViewModel

<body class="Main">
    <article>
        <div>
            <H1>Bienvenue sur DLD</H1>
        </div>
        <div>
            <H3>Le Catalogue</H3>
        </div>

        <form method="post">
            @*
                <input asp-for="SearchCriteria.ProduitName"></input>
                <input type="submit" value="Rechercher" />
            *@


            <nav class="catalog">
                <a class="item" asp-controller="Catalog" asp-action="FeL" asp-route-rayonSelector="FeL" asp-route-rayonId="1">
                    <div class="FeL2">
                    </div>
                </a>
                <a class="item" asp-controller="Catalog" asp-action="FeL" asp-route-rayonSelector="VeP" asp-route-rayonId="2">
                    <div class="VeP2">
                    </div>
                </a>
                <a class="item" asp-controller="Catalog" asp-action="FeL" asp-route-rayonSelector="PeP" asp-route-rayonId="3">
                    <div class="PeP2">
                    </div>
                </a>
                <a class="item" asp-controller="Catalog" asp-action="FeL" asp-route-rayonSelector="F" asp-route-rayonId="4">
                    <div class="F2">
                    </div>
                </a>
                <a class="item" asp-controller="Catalog" asp-action="FeL" asp-route-rayonSelector="S" asp-route-rayonId="5">
                    <div class="S2">
                    </div>
                </a>
                <a class="item" asp-controller="Catalog" asp-action="FeL" asp-route-rayonSelector="B" asp-route-rayonId="6">
                    <div class="B2">
                    </div>
                </a>
                <a class="item" asp-controller="Catalog" asp-action="FeL" asp-route-rayonSelector="ESalee" asp-route-rayonId="7">
                    <div class="ESalee2">
                    </div>
                </a>
                <a class="item" asp-controller="Catalog" asp-action="FeL" asp-route-rayonSelector="ESucree" asp-route-rayonId="8">
                    <div class="ESucree2">
                    </div>
                </a>
            </nav>
        </form>

        <div>
            <H3>Notre mission</H3>
        </div>
        <div>
            <H4>
                Notre idée fédératrice est de faciliter les dons d'excédents de légumes maraîchers et de produits en date courte.
                <br />
                <br />
                DLD a donc été mis en place pour faciliter les échanges entre les personnes afin de réduire le gaspillage et/ou les pertes de manière simple et rapide.
                L'idée maîtresse est de favoriser la mise en contact des adhérents, qu'ils soient donneurs ou bénéficiaires.
                <br />
                <br />
                Régalez-vous!
                <br />
                :)
            </H4>
        </div>
    </article>
</body>

WebApp/Views/Catalog/MesDons.cshtml
@using Fr.EQL.AI110.DLD_GC.Entities
@using Fr.EQL.AI110.DLD_GC.WebApp.Models
@model MesDonsViewModel

<div class="mesdonsselection">
    <form method="post">

        <label for="adherent">Adherent :&nbsp;</label>
        <select asp-for="SelectedAdherentId">
            <option value="" selected disabled hidden>Selectionner un adherent</option>
            <option value="0">Tous</option>
            @foreach (Adherent adherent in Model.Adherents)
            {
                <option value="@adherent.Id">@adherent.FirstName @adherent.LastName</option>
            }
        </select>
        <label for="adherent">Rôle :&nbsp;</label>
        <select asp-for="AdherentRole">
            <option value="0">Tous</option>
            <option value="1">Donateur</option>
            <option value="2">Bénéficiaire</option>

        </select>

        <input value="Filter" type="submit" />

    </form>
</div>
<div class="mesdonsresults">
    @foreach (DonDetails don in Model.Dons)
    {
        <article class="mesdonsarticle">



            <header>

                @if (don.BeneficiaryId == Model.SelectedAdherentId)
                {
                    <p>Réservé</p>
                }
                else if (don.DonorId == Model.SelectedAdherentId)
                {
                    <p>Proposé</p>

                }else{
                    <p>&nbsp</p>
                }
                
                <a style="text-decoration:none; color:black;" asp-controller="Don"
                   asp-action="Details"
                   asp-route-donId="@don.Id"
                   asp-route-adherentId="@don.DonorId">
                    <img class="mesdonsimage" src="/images/@don.DonorId/@don.Picture" alt="" onerror="this.onerror=null; this.src='/images/default.png'">
                </a>
            </header>
            <span>
                <a style="text-decoration:none; color:black;" asp-controller="Don"
                   asp-action="Details"
                   asp-route-donId="@don.Id"
                   asp-route-adherentId="@don.DonorId">
                @*<a style="text-decoration:none; color:black;" href="../Don/Details/@don.Id">*@

                    <h1>@don.ProduitName, @don.Qty @don.UniteName</h1>
                    </a>
                @*</a>*@
            </span>
            <span>
                @if (!don.Dlc.Equals(null))
                {
                    <p>DLC: @don.Dlc</p>
                }
                else if (!don.Ddm.Equals(null))
                {
                    <p>DDM: @don.Ddm</p>
                }
            </span>
            <span>
                @if (!don.AltStreetNb.Equals(null))
                {
                    <p>
                        @don.AltStreetNb @don.AltStreetName @don.AltCompAdr <br>
                        @don.DonPostcode @don.DonCity
                    </p>
                }
                else if (!don.RelStreetNb.Equals(null))
                {
                    <p>
                        @don.RelStreetNb @don.RelStreetName @don.RelCompAdr <br>
                        @don.RelaisPostcode @don.RelaisCity
                    </p>
                }
                else if (!don.PartStreetNb.Equals(null))
                {
                    <p>
                        @don.PartStreetNb @don.PartStreetName @don.PartCompAdr <br>
                        @don.PartPostcode @don.PartCity
                    </p>
                }
                else
                {
                    <p>
                        @don.DonorStreetNb @don.DonorStreetName @don.DonorCompAdr <br>
                        @don.DonorPostcode @don.DonorCity
                    </p>
                }
            </span>
        </article>
    }
</div>